unfunco/terraform-aws-oidc-github

- variables.tf
This changes the typing declaration on `var.tags` to ensure tags can be properly passed in. When defined as `object({})` the input tag contents seem to be ignored as is evident by this truncated plan:
```hcl
+ resource "aws_iam_openid_connect_provider" "github" {
+ arn             = (known after apply)
+ client_id_list  = [
+ "https://github.com/REDACTED",
+ "sts.amazonaws.com",
]
+ id              = (known after apply)
+ tags_all        = (known after apply)
+ thumbprint_list = [
+ "6938fd4d98bab03faadb97b34396831e3780aea1",
]
+ url             = "https://token.actions.githubusercontent.com"
}
```
When changed there as in this PR, there is a `tag` attribute with the expected contents.
> fix: typing on tags should be map not object

- README.md
- data.tf
- examples/complete/main.tf
- examples/complete/variables.tf
- examples/complete/versions.tf
- main.tf
- variables.tf
- versions.tf
This adds the ability to support the creation of multiple roles to this
module. Due to the fact that you can only have one OIDC provider per
URL, this module fails with a 409 error, like the below:
```
Error: error creating IAM OIDC Provider: EntityAlreadyExists: Provider
with url https://token.actions.githubusercontent.com already exists.
```
This feature is desired in the potential scenario where one wants to
create separate plan and apply roles in the same account.
To address this, we add an input variable to control whether we create
a `aws_iam_openid_connect_provider` resource or reference an existing
one using a data source. This data source was added in the AWS provider
version `4.0`, so this also includes changing the provider requirements
to that version.
Finally, this changes …
> feat: add support for creating multiple roles

- examples/complete/main.tf
- examples/complete/variables.tf
- variables.tf
Not trying to start a naming war over UK vs US spellings, but based on [GitHub's API ](https://docs.github.com/en/rest/reference/orgs) docs I feel a Z is more appropriate.
> rm unused variables, upd variable documentation.rename organisation -> organization

- data.tf
- main.tf
A fix to following error...
Terraform v1.1.0
on linux_arm64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
│ Error: Inconsistent conditional result types
│ 
│   on .terraform/modules/oidc-github/main.tf line 17, in locals:
│   17:   oidc_provider        = var.create_oidc_provider ? aws_iam_openid_connect_provider.github[0] : data.aws_iam_openid_connect_provider.github[0]
│     ├────────────────
│     │ aws_iam_openid_connect_provider.github[0] is a object, known only after apply
│     │ data.aws_iam_openid_connect_provider.github[0] is a object, known only after apply
│     │ var.create_oidc_provider is a bool, known only after apply
│ 
│ The true and false result expressions must have consistent types. The given expressions are object and object, respectively.
> Changed local.oidc_provider local.oidc_provider_arn

- variables.tf
On v0.5.0 this was possible, but the new validation broke the '*' use.
> feat: allow every repo on the organization

- main.tf
If a user adds a number of repository references from the same Org, the module would add a new client_id record for the org for each repository reference. This resolves that concern by ensuring that the client_ids list always consists of distinct records.
> Prevent duplicate client_ids records

- data.tf
- main.tf
- variables.tf
Instead of using variable for setting the certificate thumbprint, we can use data source to obtain the same.
> use data source for obtaining thumbprint

- README.md
- versions.tf
Allow `provider[registry.terraform.io/hashicorp/tls] >= 3.0`
Allow usage of tls provider version 3.x in stacks alongside this module.
Similar changes in eg. [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks): https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2211
> TLS provider version 3 plus

- variables.tf
I would like to use a wildcard in repository names so that I can allow multiple repos for a project without having to update the trust policy each time, i.e.
```            "Condition": {
"StringLike": {
"token.actions.githubusercontent.com:sub": "repo:liamfit/demo-*:*"
}
}
```
> feat: allow wildcard in repo names

- data.tf
add the recommended condition to the iam role `"token.actions.githubusercontent.com:aud": "[sts.amazonaws.com](http://sts.amazonaws.com/)"`
see aws [documentation ](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html)
> add token.actions.githubusercontent.com:aud condition

- versions.tf
After release of aws provider v 5.0.0 this module had to restrictive version constraint preventing us from using it. Ive changed version constraint to less restrictive. Terrafrom plan and terraform apply didnt pick up any changes after update so it seems to me that everything is still backwards compatible.
> Change aws provider version constraint to allow v5

- .github/workflows/ci.yaml
- CHANGELOG.md
- README.md
- data.tf
- examples/complete/main.tf
- examples/complete/variables.tf
- examples/complete/versions.tf
- main.tf
- variables.tf
Adds support for GitHub Enterprise Cloud customers by adding a new variable called `enterprise_slug` which when populated, will configure the OIDC provider with a different issuer URL, and will condition the role to be assumed only when the `iss` claim includes the enterprise slug.
> feat: Add support for GitHub Enterprise Cloud

- examples/complete/variables.tf
- variables.tf
Reduces the number of allowed `additional_thumbprints` from 4 to 3, since GitHub now returns two intermediary thumbprints for the Actions SSL certificate and the maximum number is 5.
Fixes #30
> fix: Reduce the allowed additional_thumbprints

- main.tf
I've noticed that when I pass two GitHub thumbprints that are mentioned [here](https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/) . The "autodiscovery" also adds one of them, so I finish with some duplicate thumbprints.
> fix: prevent from adding duplicate github thumbprints

- outputs.tf
Proposed fix for the [output role_arn is incompatible with aws_iam_role_policy_attachment resource](https://github.com/unfunco/terraform-aws-oidc-github/issues/36) issue
> Added role name to the outputs

- outputs.tf
In my case I want to allow additional roles to be assumed. To do that I create a new role and specify in the trust policy that the provider can assume it. For that I need the ARN of the provider :)
I have tested this change by loading my fork of the module and using the new output
> Add the ARN of the OIDC provider as output

- outputs.tf
> fix: only use OIDC provider ARN when OIDC provider is created

- .github/release-please-config.json
Sets the initial version to 1.8.0 and sets the starting SHA.
> chore: Set the first automated release version

- examples/complete/main.tf
- examples/complete/variables.tf
- main.tf
- Removes the deprecated inline policy block and replaces it with a `aws_iam_role_policy` resource. Not a breaking change
- Fixes a bug in example where enterprise_slug was a bool which created a broken OIDC provider with the URL `https://token.actions.githubusercontent.com/false`
> Swap deprecated inline_policy block for aws_iam_role_policy

- variables.tf
Closes #60 
This allows the `github_repositories` variable to have values like:
- `"acme/*:ref:refs/heads/main"`
- `"acme/*:*"`
> fix: allow wildcard in repo variable

- data.tf
- main.tf
Adds support for audiences other than sts.amazonaws.com, this determines the DNS suffix from the partition and builds the URL correctly, so that regions such as China can use the module.
> feat: Support non-default AWS partitions

- .github/workflows/pr.yaml
The CI workflow has been split into separate CI and PR workflows, and the number of Terraform versions that are tested whenever changes are made to the module has been reduced, Terraform uses semantic versioning so we will only test against the latest major.minor versions.
> chore: Split workflows and simplify testing

- README.md
- main.tf
- variables.tf
Renames the `attach_admin_policy` variable to
`dangerously_attach_admin_policy` to make it more obvious that this should be used cautiously.
> chore!: Rename the attach_admin_policy variable

- versions.tf
Bumps the minimum required version for Terraform and both the AWS and TLS providers.
> chore!: Increase the minimum required versions

- .editorconfig
- .github/workflows/pr_label.yaml
- README.md
- data.tf
- main.tf
- outputs.tf
- variables.tf
This is not really necessary, the count feature in Terraform provides similar functionality, it's recommended to use that instead.
> chore!: Remove the enabled variable

- README.md
- data.tf
- main.tf
- outputs.tf
- variables.tf
The module previously created a role automatically, and allowed managed policies and inline policies to be attached to the role, this works well for simple setups but makes it difficult to do multiple account/multiple role OIDC configurations.
> feat: Add a flag to enable/disable role creation

- .github/workflows/ci.yaml
- README.md
- oidc-github.tftest.hcl
Add a variable to fix a broken unit test.
> fix: Fix broken unit test

- main.tf
This fixes a bug where adding custom policies would instead add the AdministratorAccess policy.
It looks like this was mistakenly overridden in 6c252cf48fdf60bba543b6280d19d0ec22b2ee1b.
> fix: custom policies

- .github/workflows/ci.yaml
- README.md
- examples/basic/versions.tf
- examples/multiple-roles/versions.tf
- versions.tf
Reduces the minimum required Terraform version to 1.0, testing requires a later version so the workflow versions have not been reduced.
Fixes #89
> fix: Reduce the minimum Terraform version required
